[build]
  publish = "build/web"
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
    export PATH="$PATH:$HOME/flutter/bin"
    flutter doctor --disable-analytics
    flutter pub get
    flutter build web --release
  """

[build.environment]
  FLUTTER_VERSION = "stable"